name: TROPOMI_inversion
channels:
  - intel
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - cartopy=0.17.0
  - cloudpickle=1.6.0
  - dask=2021.1.0
  - esmf=8.0.1
  - geos=3.8.1
  - h5py=2.10.0
  - hdf4=4.2.13
  - hdf5=1.10.6
  - ipython=7.19.0
  - matplotlib=3.2.2
  - netcdf-fortran=4.5.3
  - netcdf4=1.5.5.1
  - numpy=1.19.1
  - pandas=1.1.0
  - pickleshare=0.7.5
  - pillow=7.2.0
  - pip=20.2.4
  - python=3.8.5
  - scikit-learn=0.23.1
  - scipy=1.5.2
  - shapely=1.7.1
  - xarray=0.16.2
  - xbpch=0.3.5
  - xesmf=0.3.0