name: TROPOMI_inversion
channels:
  - intel
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - cartopy=0.17.0
  - esmf=8.0.1
  - geos=3.8.1
  - hdf5=1.10.6
  - matplotlib=3.2.2
  - netcdf-fortran=4.5.3
  - netcdf4=1.5.4
  - numpy=1.19.1
  - pandas=1.1.0
  - pillow=7.2.0
  - pip=20.2
  - python=3.8.5
  - scikit-learn=0.23.1
  - scipy=1.5.2
  - xarray=0.16.0
  - xesmf=0.3.0
