name: TROPOMI_inversion
channels:
  - intel
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - cartopy=0.17.0
  - dask=2021.1.0
  - h5py=2.10.0
  - ipython=7.19.0
  - matplotlib=3.2.2
  - netcdf4=1.5.5
  - numpy=1.19.1
  - pandas=1.1.0
  - pip=20.2.4
  - python=3.8.5
  - scikit-learn=0.23.1
  - scipy=1.5.2
  - shapely=1.7.1
  - xarray=0.16.2
  - xbpch=0.3.5
  - xesmf=0.3.0
  - blas=1.1
