# Figure sizes
SCALE = 1
PRES_SCALE = 2
# BASE_FIG_SIZE = 6
BASE_WIDTH = 7
BASE_HEIGHT = 6
PRES_WIDTH = 5
PRES_HEIGHT = 4.3

# Fontsizes
TITLE_FONTSIZE = 15 # 18
SUBTITLE_FONTSIZE = 13 # 14
LABEL_FONTSIZE = 11 # 12
TICK_FONTSIZE = 9 # 10

# Presentation fontsizes
PRES_TITLE_FONTSIZE = 14
PRES_SUBTITLE_FONTSIZE = 12
PRES_LABEL_FONTSIZE = 10
PRES_TICK_FONTSIZE = 8

# Position
TITLE_LOC = 1
TITLE_PAD = 10
CBAR_PAD = 0.05
LABEL_PAD = 20
CBAR_LABEL_PAD = 30

# Default colors
